apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
  labels:
    name: configmap-demo
spec:
  containers:
  - name: configmap-demo
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ['sh', '-c', 'env']
    envFrom: 
      - configMapRef:
          name: special-config
  restartPolicy: Never
