apiVersion: v1
kind: Pod
metadata:
  name: dependent-envars
  labels:
    name: dependent-envars
spec:
  containers:
  - name: dependent-envars
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ['sh', '-c']
    args: 
      - printf UNCHANGED_REFERENCE=$UNCHANGED_REFERENCE'\n'; printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n'; printf ESCAPED_REFERENCE=$ESCAPED_REFERENCE'\n'; 
    env:
      - name: SERVICE_PORT
        value: "80"
      - name: SERVICE_IP
        value: "172.17.0.1"
      - name: UNCHANGED_REFERENCE
        value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
      - name: PROTOCOL
        value: "https"
      - name: SERVICE_ADDRESS
        value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
      - name: ESCAPED_REFERENCE
        value: "$$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
