apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    name: init-pod
spec:
  containers:
  - name: init-pod
    image: busybox
    command: ['sh', '-c', 'date && sleep 3600']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'date && sleep 10']
